EXPERIMENT_NAME = 'transformer'
WORKING_DIR ="/home/Ravikumar/Developer/text_generation/"
CHECKPOINTS_DIR = WORKING_DIR +"checkpoints/"
DATA_DIR = WORKING_DIR + "dataset/"
DEFAULT_FILE_NAME = DATA_DIR + "joke.csv"
# TRIM_SIZE = 10 # check the plot in the result
N_HIDDEN = 128
LR = 0.0001
EMB_DIM = 512
BATCH_SIZE = 64
SEQ_LEN = 5
N_EPOCHS = 500
CHECKPOINT_NAME = f"/{EXPERIMENT_NAME}-batch_size_{BATCH_SIZE}-emb_dim_{EMB_DIM}-hidden_size_{N_HIDDEN}_"
NUM_LAYERS = 3
PATIENCE = 5
DEVICE = "cuda"
N_HEADS = 16
ENCODER_LAYERS = 12
TOKENIZER_TYPE = "spacy"
DROPOUT = 0.1
N_LAYERS = 6
N_HEADS = 8